/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Navigator = new javax.swing.JPanel();
        Nav = new javax.swing.JLabel();
        LS = new javax.swing.JButton();
        ASL = new javax.swing.JButton();
        SF = new javax.swing.JButton();
        UDS = new javax.swing.JButton();
        NS = new javax.swing.JButton();
        MR = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navigator.setBackground(new java.awt.Color(204, 204, 255,90));
        Navigator.setPreferredSize(new java.awt.Dimension(280, 500));

        Nav.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Nav.setText("      NAVIGATOR BAR");

        LS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/leaved std.png"))); // NOI18N
        LS.setText("Leaved Students");
        LS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSActionPerformed(evt);
            }
        });

        ASL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/All std leaving.png"))); // NOI18N
        ASL.setText("All Student Living");
        ASL.setMaximumSize(new java.awt.Dimension(149, 39));
        ASL.setMinimumSize(new java.awt.Dimension(149, 39));
        ASL.setPreferredSize(new java.awt.Dimension(149, 39));
        ASL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASLActionPerformed(evt);
            }
        });

        SF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/payment.png"))); // NOI18N
        SF.setText("Student Fees");
        SF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SFActionPerformed(evt);
            }
        });

        UDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/U & D.png"))); // NOI18N
        UDS.setText("Update & Delete Students");
        UDS.setMaximumSize(new java.awt.Dimension(149, 39));
        UDS.setMinimumSize(new java.awt.Dimension(149, 39));
        UDS.setPreferredSize(new java.awt.Dimension(149, 39));
        UDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UDSActionPerformed(evt);
            }
        });

        NS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/new student.png"))); // NOI18N
        NS.setText("New Student");
        NS.setMaximumSize(new java.awt.Dimension(149, 39));
        NS.setMinimumSize(new java.awt.Dimension(149, 39));
        NS.setPreferredSize(new java.awt.Dimension(149, 39));
        NS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSActionPerformed(evt);
            }
        });

        MR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/room.png"))); // NOI18N
        MR.setText("Manage Room");
        MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigatorLayout = new javax.swing.GroupLayout(Navigator);
        Navigator.setLayout(NavigatorLayout);
        NavigatorLayout.setHorizontalGroup(
            NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigatorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MR, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NS, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UDS, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ASL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LS, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        NavigatorLayout.setVerticalGroup(
            NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(MR)
                .addGap(18, 18, 18)
                .addComponent(NS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SF)
                .addGap(18, 18, 18)
                .addComponent(ASL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LS)
                .addGap(40, 40, 40))
        );

        getContentPane().add(Navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 430));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/backg.png"))); // NOI18N
        Background.setText("jLabel1");
        Background.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Background.setMinimumSize(new java.awt.Dimension(1920, 1080));
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRActionPerformed
        // TODO add your handling code here:
        new ManageRoom().setVisible(true);
    }//GEN-LAST:event_MRActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Login().setVisible(true);
            
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"Do you really want to Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
           System.exit(0);
            
        }
                 
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void NSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NSActionPerformed
        // TODO add your handling code here:
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_NSActionPerformed

    private void UDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UDSActionPerformed
        // TODO add your handling code here:
         new UpdateDeleteStudents().setVisible(true);
    }//GEN-LAST:event_UDSActionPerformed

    private void SFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SFActionPerformed
        // TODO add your handling code here:
         new StudentFees().setVisible(true);
    }//GEN-LAST:event_SFActionPerformed

    private void LSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSActionPerformed
        // TODO add your handling code here:
         new LeavedStudents().setVisible(true);
    }//GEN-LAST:event_LSActionPerformed

    private void ASLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASLActionPerformed
        // TODO add your handling code here:
         new AllStudentsLiving().setVisible(true);
    }//GEN-LAST:event_ASLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ASL;
    private javax.swing.JLabel Background;
    private javax.swing.JButton LS;
    private javax.swing.JButton MR;
    private javax.swing.JButton NS;
    private javax.swing.JLabel Nav;
    private javax.swing.JPanel Navigator;
    private javax.swing.JButton SF;
    private javax.swing.JButton UDS;
    private javax.swing.JButton exit;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
