/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagement;

import java.awt.Color;
//import javax.swing.JButton;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.DBConnection;

/**
 *
 * @author Acer
 */
public class ManageRoom extends javax.swing.JFrame {
    
    public void clear()
    {
        RoomNT.setText("");
        RoomNumT.setText("");
        Yes.setSelected(false);
        YesR.setSelected(false);
//        RoomNumT.setBackground(new JButton().getBackground());
//        RoomNumT.setForeground(new JButton().getForeground());
        RoomNumT.setEditable(true);
    }
    public void tableDetails(){
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        try{
            Connection con =DBConnection.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from room");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
  
    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
        tableDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewRoom = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        Table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RoomN = new javax.swing.JLabel();
        RoomNT = new javax.swing.JTextField();
        AOD = new javax.swing.JLabel();
        Yes = new javax.swing.JCheckBox();
        Save = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        UDRoom = new javax.swing.JLabel();
        RoomNum = new javax.swing.JLabel();
        RoomNumT = new javax.swing.JTextField();
        AODR = new javax.swing.JLabel();
        YesR = new javax.swing.JCheckBox();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        AllRoom = new javax.swing.JLabel();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewRoom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NewRoom.setText("Add New Room");
        getContentPane().add(NewRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/close.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Number", "Activate", "Roomstatus"
            }
        ));
        Table.setViewportView(jTable1);

        getContentPane().add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, 110));

        RoomN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomN.setText("Room Number");
        getContentPane().add(RoomN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        RoomNT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(RoomNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        AOD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AOD.setText("Activate or Deactivate");
        getContentPane().add(AOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        Yes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Yes.setText("Yes");
        Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesActionPerformed(evt);
            }
        });
        getContentPane().add(Yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Save.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 695, 10));

        UDRoom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UDRoom.setText("Update & Delete Room");
        getContentPane().add(UDRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, -1, -1));

        RoomNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomNum.setText("Room Number");
        getContentPane().add(RoomNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, -1, -1));

        RoomNumT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomNumT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumTActionPerformed(evt);
            }
        });
        getContentPane().add(RoomNumT, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 149, 112, -1));

        AODR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AODR.setText("Activate or Deactivate");
        getContentPane().add(AODR, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 152, -1, -1));

        YesR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YesR.setText("Yes");
        getContentPane().add(YesR, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 148, -1, -1));

        Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 148, -1, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Save.png"))); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 195, -1, -1));

        Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Delete.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 195, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 690, -1));

        AllRoom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        AllRoom.setText("All Rooms");
        getContentPane().add(AllRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/MRBackground.png"))); // NOI18N
        getContentPane().add(Backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoomNumTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNumTActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
       setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
//       String RoomNumber=RoomNT.getText();
        String number=RoomNT.getText();
        String activate;
        String roomstatus="Not Booked";
                if(Yes.isSelected())
            {
                activate="Yes";
            }
            else
                activate="No";
                try
                {
                    Connection con=DBConnection.getCon();
                    PreparedStatement ps=con.prepareStatement("insert into room values(?,?,?)");

                ps.setString(1,number);
                ps.setString(2,activate);
                 ps.setString(3,roomstatus);
                 ps.executeUpdate();
                 JOptionPane.showMessageDialog(null,"Sucessfully Updated");
                 tableDetails();
                 clear();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
    }//GEN-LAST:event_SaveActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String number=RoomNumT.getText();
        int i=0;
        try
        {
            Connection con=DBConnection.getCon();
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select *from room where number='"+number+"'");
            while(rs.next())
            {
                i=1;
                if(rs.getString(3).equals("Booked"))
                {
                    JOptionPane.showMessageDialog(null,"This Room is booked");
                    clear();
                }
//                else if(rs.getString(3).equals("Not Booked"))
//                {
//                    JOptionPane.showMessageDialog(null, "this room is not booked");
//                    clear();
//                }
                else{
                    RoomNumT.setEditable(false);
//                   
                    if(rs.getString(2).equals("Yes"))
                        
                        YesR.setSelected(true);
                   
                    else
                        YesR.setSelected(false);
                }
            }
            
            if(i==0)
            {
              JOptionPane.showMessageDialog(null,"Room Number Does not Exist");
              clear();
            }
        }
        catch (Exception e){
            
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String number=RoomNumT.getText();
        String activate;
        if (YesR.isSelected())
            activate= "Yes";
        else
            activate="No";
        try{
            Connection con=DBConnection.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("Update room set activate'"+activate+"'where number = '"+number+"'");
//             PreparedStatement ps = con.prepareStatement("UPDATE room SET activate '"+activate+"' = WHERE number ='"+number+"'");
           
            JOptionPane.showMessageDialog(null,"Sucessfully Update");
            tableDetails();
            clear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         String number=RoomNumT.getText();
         try{
            Connection con=DBConnection.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("delete from room where number = '"+number+"'");
            JOptionPane.showMessageDialog(null,"Sucessfully Delete");
            tableDetails();
            clear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AOD;
    private javax.swing.JLabel AODR;
    private javax.swing.JLabel AllRoom;
    private javax.swing.JLabel Backgroud;
    private javax.swing.JButton Close;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel NewRoom;
    private javax.swing.JLabel RoomN;
    private javax.swing.JTextField RoomNT;
    private javax.swing.JLabel RoomNum;
    private javax.swing.JTextField RoomNumT;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JScrollPane Table;
    private javax.swing.JLabel UDRoom;
    private javax.swing.JButton Update;
    private javax.swing.JCheckBox Yes;
    private javax.swing.JCheckBox YesR;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
