/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagement;
import java.sql.*;
import javax.swing.JOptionPane;
import project.DBConnection;
/**
 *
 * @author Acer
 */
public class NewStudent extends javax.swing.JFrame {
public void clear()
{

    NameT.setText("");
    FatherT.setText("");
    MotherT.setText("");
    EmailT.setText("");
    PermanentT.setText("");
    CollegeT.setText("");
    MobileT.setText("");
    RoomCB.removeAllItems();
    roomnumber();
    
}

public void roomnumber(){
    int i=0;
    try{
         Connection con =DBConnection.getCon();
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select *from room where activate='Yes' and roomstatus='Not Booked'");
          while(rs.next())
          {
              i=1;
              RoomCB.addItem(rs.getString(1));
            }
          
          if(i==0)
          {
              Save.setVisible(false);
              JOptionPane.showMessageDialog(null, "All Rooms are already Booked");
              setVisible(false);
          }
    }
    catch(Exception e){
        
    }
}
    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close = new javax.swing.JButton();
        NameL = new javax.swing.JLabel();
        FatherL = new javax.swing.JLabel();
        MotherL = new javax.swing.JLabel();
        EmailL = new javax.swing.JLabel();
        PermanentL = new javax.swing.JLabel();
        CollegeL = new javax.swing.JLabel();
        MobileL = new javax.swing.JLabel();
        RoomL = new javax.swing.JLabel();
        NameT = new javax.swing.JTextField();
        FatherT = new javax.swing.JTextField();
        MotherT = new javax.swing.JTextField();
        EmailT = new javax.swing.JTextField();
        PermanentT = new javax.swing.JTextField();
        CollegeT = new javax.swing.JTextField();
        MobileT = new javax.swing.JTextField();
        RoomCB = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/close.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        NameL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameL.setText("Name");
        getContentPane().add(NameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 137, 131, -1));

        FatherL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FatherL.setText("Father Name");
        getContentPane().add(FatherL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 181, 131, -1));

        MotherL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MotherL.setText("Mother Name");
        getContentPane().add(MotherL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 225, 131, -1));

        EmailL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailL.setText("Email");
        getContentPane().add(EmailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 266, 131, -1));

        PermanentL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PermanentL.setText("Permanent Address");
        getContentPane().add(PermanentL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 307, -1, -1));

        CollegeL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CollegeL.setText("College Name");
        getContentPane().add(CollegeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 351, 131, -1));

        MobileL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileL.setText("Mobile Number");
        getContentPane().add(MobileL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 392, 131, -1));

        RoomL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomL.setText("Room Number");
        getContentPane().add(RoomL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 131, -1));

        NameT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(NameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 134, 325, -1));

        FatherT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FatherT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherTActionPerformed(evt);
            }
        });
        getContentPane().add(FatherT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 178, 325, -1));

        MotherT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(MotherT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 222, 325, -1));

        EmailT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(EmailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 260, 325, -1));

        PermanentT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(PermanentT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 304, 325, -1));

        CollegeT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(CollegeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 348, 325, -1));

        MobileT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileTActionPerformed(evt);
            }
        });
        getContentPane().add(MobileT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 386, 325, -1));

        RoomCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCBActionPerformed(evt);
            }
        });
        getContentPane().add(RoomCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 430, 325, -1));

        Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Save.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/small clear.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/MRBackground.png"))); // NOI18N
        Background.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BackgroundComponentShown(evt);
            }
        });
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FatherTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherTActionPerformed

    private void RoomCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomCBActionPerformed

    private void MobileTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileTActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void BackgroundComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BackgroundComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_BackgroundComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        roomnumber();
    }//GEN-LAST:event_formComponentShown

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        String name=NameT.getText();
        String father=FatherT.getText();
        String mother=MotherT.getText();
        String email=EmailT.getText();
        String address=PermanentT.getText();
        String college=CollegeT.getText();
        String mobileno=MobileT.getText();       
        String roomnumber=(String)RoomCB.getSelectedItem();
        String status="living";
        try{
           Connection con =DBConnection.getCon();
            Statement stmt = con.createStatement();
            stmt.executeUpdate("Insert into student(name,father,mother,email,address,college,mobileno,roomno,status)" 
                    +"values('"+name+"','"+father+"','"+mother+"','"+email+"','"+address+"','"+college+"','"+mobileno+"','"+roomnumber+"','"+status+"')"); 
             clear();
             
             PreparedStatement ps = con.prepareStatement("UPDATE room SET roomstatus = ? WHERE number ='"+roomnumber+"'");
             ps.setString(1,"Booked");
             ps.executeUpdate();
             JOptionPane.showMessageDialog(null,name+"Your room "+roomnumber+" is Booked");
        }
        catch(Exception e){
           
            JOptionPane.showMessageDialog(null,e);  
       
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        clear();
   
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Close;
    private javax.swing.JLabel CollegeL;
    private javax.swing.JTextField CollegeT;
    private javax.swing.JLabel EmailL;
    private javax.swing.JTextField EmailT;
    private javax.swing.JLabel FatherL;
    private javax.swing.JTextField FatherT;
    private javax.swing.JLabel MobileL;
    private javax.swing.JTextField MobileT;
    private javax.swing.JLabel MotherL;
    private javax.swing.JTextField MotherT;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameT;
    private javax.swing.JLabel PermanentL;
    private javax.swing.JTextField PermanentT;
    private javax.swing.JComboBox<String> RoomCB;
    private javax.swing.JLabel RoomL;
    private javax.swing.JButton Save;
    // End of variables declaration//GEN-END:variables
}
