/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagement;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import project.DBConnection;
/**
 *
 * @author Acer
 */
public class StudentFees extends javax.swing.JFrame {
 public void clear(){
     IDT.setVisible(true);
     IDT.setText("");
     NameT.setText("");
     EmailT.setText("");
     MobileT.setText("");
     RoomT.setText("");
     MonthT.setText("");
     AmountT.setText("");
     DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
     dtm.setRowCount(0);
 }
 public void tableDetails()
 {
   DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();  
    dtm.setRowCount(0);
    String IDL=IDT.getText();
//     String mobileno=MobileT.getText();

    try
    {
        Connection con =DBConnection.getCon();
         Statement st=con.createStatement();
//           ResultSet rs=st.executeQuery("select *from room where mobileno='"+mobileno+"'");
             ResultSet rs=st.executeQuery("select *from room where IDL='"+IDL+"'");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString(2),rs.getString(3)});
            }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}
    /**
     * Creates new form StudentFees
     */
    public StudentFees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Close = new javax.swing.JButton();
        IDL = new javax.swing.JLabel();
        IDT = new javax.swing.JTextField();
        NameL = new javax.swing.JLabel();
        EmailL = new javax.swing.JLabel();
        MobileL = new javax.swing.JLabel();
        RoomL = new javax.swing.JLabel();
        MonthL = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        NameT = new javax.swing.JTextField();
        EmailT = new javax.swing.JTextField();
        MobileT = new javax.swing.JTextField();
        RoomT = new javax.swing.JTextField();
        MonthT = new javax.swing.JTextField();
        AmountT = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        AmountL = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Month", "Amount"
            }
        ));
        Table.setViewportView(jTable1);

        getContentPane().add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 700, 130));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/close.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 0, -1, -1));

        IDL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDL.setText("ID");
        getContentPane().add(IDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 53, 121, -1));

        IDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(IDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 50, 261, -1));

        NameL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameL.setText("Name");
        getContentPane().add(NameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 107, 121, -1));

        EmailL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailL.setText("Email");
        getContentPane().add(EmailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 151, 121, -1));

        MobileL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileL.setText("Mobile Number");
        getContentPane().add(MobileL, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 195, 121, -1));

        RoomL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomL.setText("Room Number");
        getContentPane().add(RoomL, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 239, 121, -1));

        MonthL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MonthL.setText("Month");
        getContentPane().add(MonthL, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 283, -1, -1));

        Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Save.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        NameT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(NameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 104, 339, -1));

        EmailT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(EmailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 148, 339, -1));

        MobileT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileTActionPerformed(evt);
            }
        });
        getContentPane().add(MobileT, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 192, 339, -1));

        RoomT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(RoomT, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 236, 339, -1));

        MonthT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(MonthT, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 280, 339, -1));

        AmountT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(AmountT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 340, -1));

        Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 49, -1, -1));

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/small clear.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        AmountL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AmountL.setText("Amount to be pay");
        getContentPane().add(AmountL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/MRBackground.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void MobileTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileTActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
         String id=IDT.getText();
//           String mobileno=MobileT.getText();
         SimpleDateFormat dFormat=new SimpleDateFormat("MMM-YYY");
         Date date=new Date();
         String month=dFormat.format(date);
         try{
          Connection con =DBConnection.getCon();
          Statement st=con.createStatement();  
          ResultSet rs=st.executeQuery ("select *from student where id= '"+id+"' and status='living'");
//            ResultSet rs=st.executeQuery ("select *from student where id= "+MobileL+"' and status='living'");
JOptionPane.showMessageDialog(null, "id Found");
if(rs.first())
          {
//              IDT.setVisible(true);
//              IDT.setText(rs.getString(1));
//              NameT.setText(rs.getString(2));
//              FatherT.setText(rs.getString(3));
//              MotherT.setText(rs.getString(4));
//              EmailT.setText(rs.getString(5));
//              PermanentT.setText(rs.getString(6));
//              CollegeT.setText(rs.getString(7));
//              MobileT.setText(rs.getString(8));
//              RoomT.setText(rs.getString(9));
              IDT.setEditable(false);
//              IDT.setVisible(true);
//              IDT.setText(rs.getString(1));
              NameT.setText(rs.getString(2));
              EmailT.setText(rs.getString(5));
              MobileT.setText(rs.getString(8));
              RoomT.setText(rs.getString(9));
              MonthT.setText(month);
              
              AmountT.setText("6000");
          }
          else{
              JOptionPane.showMessageDialog(null,"Student does not Exist");
              clear();
          }
          tableDetails();
          
//          ResultSet rs1=st.executeQuery("select *from fees inner join student where student.status='living' and fees.month='"+month+"' and fees.mobileno='"+mobileno+"'and student.mobileno='"+mobileno+"'");
            ResultSet rs1=st.executeQuery("select *from fees inner join student where student.status='living' and fees.month='"+month+"' and fees.id='"+id+"'and student.id='"+id+"'");
         if(rs1.first())
         {
             Save.setVisible(false);
             JOptionPane.showMessageDialog(null,"Fees is already paid by student for this month");
         }
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_SearchActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String id=IDT.getText();
        String mobileno=MobileT.getText();
        String month=MonthT.getText(); 
        String amount=AmountT.getText();
        try{
            Connection con =DBConnection.getCon();
            PreparedStatement ps=con.prepareStatement("insert into fees values(?,?,?)");
            ps.setString(1,id);
            ps.setString(2,mobileno);
            ps.setString(3,month);
            ps.setString(4,amount);
            ps.executeUpdate();
            tableDetails();
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            clear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountL;
    private javax.swing.JTextField AmountT;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Close;
    private javax.swing.JLabel EmailL;
    private javax.swing.JTextField EmailT;
    private javax.swing.JLabel IDL;
    private javax.swing.JTextField IDT;
    private javax.swing.JLabel MobileL;
    private javax.swing.JTextField MobileT;
    private javax.swing.JLabel MonthL;
    private javax.swing.JTextField MonthT;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameT;
    private javax.swing.JLabel RoomL;
    private javax.swing.JTextField RoomT;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JScrollPane Table;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
