/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagement;
import java.sql.*;
import javax.swing.JOptionPane;
import project.DBConnection;
/**
 *
 * @author Acer
 */
public class UpdateDeleteStudents extends javax.swing.JFrame {
 public void clear(){
//     ID.setEditable(true);
     ID.setVisible(true);
     IDT.setText("");
     NameT.setText("");
     FatherT.setText("");
     MotherT.setText("");
     EmailT.setText("");
     PermanentT.setText("");
     CollegeT.setText("");
     MobileT.setText("");
     RoomT.setText("");
     LivingCB.removeAllItems();
 }
    /**
     * Creates new form UpdateDeleteStudents
     */
    public UpdateDeleteStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        FatherL = new javax.swing.JLabel();
        MotherL = new javax.swing.JLabel();
        IDT = new javax.swing.JTextField();
        EmailL = new javax.swing.JLabel();
        PermanentL = new javax.swing.JLabel();
        CollegeL = new javax.swing.JLabel();
        MobileL = new javax.swing.JLabel();
        RoomL = new javax.swing.JLabel();
        LivingL = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        NameT = new javax.swing.JTextField();
        FatherT = new javax.swing.JTextField();
        MotherT = new javax.swing.JTextField();
        EmailT = new javax.swing.JTextField();
        PermanentT = new javax.swing.JTextField();
        CollegeT = new javax.swing.JTextField();
        MobileT = new javax.swing.JTextField();
        RoomT = new javax.swing.JTextField();
        LivingCB = new javax.swing.JComboBox<>();
        Search = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 100));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/close.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 0, -1, -1));

        ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ID.setText("ID");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 63, 131, -1));

        NameL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameL.setText("Name");
        getContentPane().add(NameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 105, 131, -1));

        FatherL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FatherL.setText("Father Name");
        getContentPane().add(FatherL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 149, 131, -1));

        MotherL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MotherL.setText("Mother Name");
        getContentPane().add(MotherL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 193, 131, -1));

        IDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(IDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 55, 212, -1));

        EmailL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailL.setText("Email");
        getContentPane().add(EmailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 237, 131, -1));

        PermanentL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PermanentL.setText("Permanent Address");
        getContentPane().add(PermanentL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 281, -1, -1));

        CollegeL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CollegeL.setText("College Name");
        getContentPane().add(CollegeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 325, 131, -1));

        MobileL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileL.setText("Mobile Number");
        getContentPane().add(MobileL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 369, 131, -1));

        RoomL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomL.setText("Room Number");
        getContentPane().add(RoomL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 413, 131, -1));

        LivingL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LivingL.setText("Living Status");
        getContentPane().add(LivingL, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 458, 131, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Save.png"))); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 500, -1, -1));

        NameT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(NameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 102, 295, -1));

        FatherT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(FatherT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 146, 295, -1));

        MotherT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(MotherT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 190, 295, -1));

        EmailT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(EmailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 234, 295, -1));

        PermanentT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(PermanentT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 278, 295, -1));

        CollegeT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(CollegeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 322, 295, -1));

        MobileT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(MobileT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 366, 295, -1));

        RoomT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(RoomT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 410, 295, -1));

        LivingCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LivingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivingCBActionPerformed(evt);
            }
        });
        getContentPane().add(LivingCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 295, -1));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 56, -1, -1));

        Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Delete.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 500, -1, -1));

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/small clear.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/MRBackground.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String ID=IDT.getText();
        try{
         Connection con =DBConnection.getCon();
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery ("select *from student where id='"+ID+"'");
         if(rs.next())
         {
//              ID.setEditable(false);
              IDT.setVisible(true);
              IDT.setText(rs.getString(1));
              NameT.setText(rs.getString(2));
              FatherT.setText(rs.getString(3));
              MotherT.setText(rs.getString(4));
              EmailT.setText(rs.getString(5));
              PermanentT.setText(rs.getString(6));
              CollegeT.setText(rs.getString(7));
              MobileT.setText(rs.getString(8));
              RoomT.setText(rs.getString(9));
              if(rs.getString(10).equals("living"))
              {
                  LivingCB.addItem("living");
                  LivingCB.addItem("leaved");
              }
              else{
                  LivingCB.addItem("leaved");
                  LivingCB.addItem("living");
              }
         }
         else{
             JOptionPane.showMessageDialog(null, "Student does not Exist");
             clear(); 
         }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
      String id=IDT.getText();
      String name=NameT.getText();
      String father=FatherT.getText();
      String mother=MotherT.getText();
      String email=EmailT.getText();
      String address=PermanentT.getText();
      String college=CollegeT.getText();
      String mobileno=MobileT.getText();
      String roomno=RoomT.getText();
      String status=(String)LivingCB.getSelectedItem();
      try{
         Connection con =DBConnection.getCon();
         Statement st=con.createStatement();
//         if(status.equals("living")){
//           st.executeUpdate("update roomset roomstatus='Booked' where Number='"+roomno+"'");
//         }   else{
//           st.executeUpdate("update roomset roomstatus='Not Booked' where Number='"+roomno+"'");
//         }
        PreparedStatement ps=con.prepareStatement("update student set name=?, father=?,mother=?,email=?,address=?,college=?,mobileno=?,status=? where id=?") ;
        ps.setString(1,name);
        ps.setString(2,father); 
        ps.setString(3,mother);
        ps.setString(4,email); 
        ps.setString(5,address); 
        ps.setString(6,college); 
        ps.setString(7,mobileno); 
        ps.setString(8,status); 
        ps.setString(9,id); 
        ps.executeUpdate();
    
        JOptionPane.showMessageDialog(null,"Sucessfully Updated");
        clear();
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          System.out.println(e);
      }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String id=IDT.getText();
        String roomno=RoomT.getText();
        try{
         Connection con =DBConnection.getCon();
         Statement st=con.createStatement();
         st.executeUpdate("delete from student where id = '"+id+"'");
         
         JOptionPane.showMessageDialog(null,"Sucessfully Deleted");
         clear();
         
          PreparedStatement ps = con.prepareStatement("UPDATE room SET roomstatus = ? WHERE number ='"+roomno+"'");
             ps.setString(1,"Not Booked");
             ps.executeUpdate();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
     clear();
//     ID.setEditable(true);
     ID.setVisible(true);
     IDT.setText("");
     NameT.setText("");
     FatherT.setText("");
     MotherT.setText("");
     EmailT.setText("");
     PermanentT.setText("");
     CollegeT.setText("");
     IDT.setText("");
     RoomT.setText("");
     LivingCB.removeAllItems();
    }//GEN-LAST:event_ClearActionPerformed

    private void LivingCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivingCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LivingCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Close;
    private javax.swing.JLabel CollegeL;
    private javax.swing.JTextField CollegeT;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel EmailL;
    private javax.swing.JTextField EmailT;
    private javax.swing.JLabel FatherL;
    private javax.swing.JTextField FatherT;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDT;
    private javax.swing.JComboBox<String> LivingCB;
    private javax.swing.JLabel LivingL;
    private javax.swing.JLabel MobileL;
    private javax.swing.JTextField MobileT;
    private javax.swing.JLabel MotherL;
    private javax.swing.JTextField MotherT;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameT;
    private javax.swing.JLabel PermanentL;
    private javax.swing.JTextField PermanentT;
    private javax.swing.JLabel RoomL;
    private javax.swing.JTextField RoomT;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    // End of variables declaration//GEN-END:variables
}
